// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generators.Compressors
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CompressorsGenerator : CompressorsGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using NetStack.Compression;\r\n\r\npublic static class ");
            
            #line 9 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write("Compressors\r\n{\r\n");
            
            #line 11 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"

for (int i = 0; i < Mins.Length; i++)
{
    var name = CompressorNames[i];
	
            
            #line default
            #line hidden
            this.Write("\tpublic static readonly BoundedRange ");
            
            #line 16 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Compressor;\r\n\t");
            
            #line 17 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"

}

            
            #line default
            #line hidden
            this.Write("    \r\n    static ");
            
            #line 21 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write("Compressors()\r\n    {\r\n");
            
            #line 23 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"

for (int i = 0; i < Mins.Length; i++)
{
    var name = CompressorNames[i];
    var min = Mins[i];
    var max = Maxs[i];
    var precision = Precisions[i];
    
            
            #line default
            #line hidden
            this.Write("\t    ");
            
            #line 31 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Compressor = new BoundedRange(");
            
            #line 31 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(min));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 31 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(max));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 31 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(precision));
            
            #line default
            #line hidden
            this.Write("f);\r\n\t");
            
            #line 32 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"

}

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\UnityProjects\Coop-JRPG-git\Generators\Generators\Generators\Compressors\CompressorsGenerator.tt"

private string _PrefixField;

/// <summary>
/// Access the Prefix parameter of the template.
/// </summary>
private string Prefix
{
    get
    {
        return this._PrefixField;
    }
}

private string[] _CompressorNamesField;

/// <summary>
/// Access the CompressorNames parameter of the template.
/// </summary>
private string[] CompressorNames
{
    get
    {
        return this._CompressorNamesField;
    }
}

private float[] _MinsField;

/// <summary>
/// Access the Mins parameter of the template.
/// </summary>
private float[] Mins
{
    get
    {
        return this._MinsField;
    }
}

private float[] _MaxsField;

/// <summary>
/// Access the Maxs parameter of the template.
/// </summary>
private float[] Maxs
{
    get
    {
        return this._MaxsField;
    }
}

private float[] _PrecisionsField;

/// <summary>
/// Access the Precisions parameter of the template.
/// </summary>
private float[] Precisions
{
    get
    {
        return this._PrecisionsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool PrefixValueAcquired = false;
if (this.Session.ContainsKey("Prefix"))
{
    this._PrefixField = ((string)(this.Session["Prefix"]));
    PrefixValueAcquired = true;
}
if ((PrefixValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Prefix");
    if ((data != null))
    {
        this._PrefixField = ((string)(data));
    }
}
bool CompressorNamesValueAcquired = false;
if (this.Session.ContainsKey("CompressorNames"))
{
    this._CompressorNamesField = ((string[])(this.Session["CompressorNames"]));
    CompressorNamesValueAcquired = true;
}
if ((CompressorNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("CompressorNames");
    if ((data != null))
    {
        this._CompressorNamesField = ((string[])(data));
    }
}
bool MinsValueAcquired = false;
if (this.Session.ContainsKey("Mins"))
{
    this._MinsField = ((float[])(this.Session["Mins"]));
    MinsValueAcquired = true;
}
if ((MinsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Mins");
    if ((data != null))
    {
        this._MinsField = ((float[])(data));
    }
}
bool MaxsValueAcquired = false;
if (this.Session.ContainsKey("Maxs"))
{
    this._MaxsField = ((float[])(this.Session["Maxs"]));
    MaxsValueAcquired = true;
}
if ((MaxsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Maxs");
    if ((data != null))
    {
        this._MaxsField = ((float[])(data));
    }
}
bool PrecisionsValueAcquired = false;
if (this.Session.ContainsKey("Precisions"))
{
    this._PrecisionsField = ((float[])(this.Session["Precisions"]));
    PrecisionsValueAcquired = true;
}
if ((PrecisionsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Precisions");
    if ((data != null))
    {
        this._PrecisionsField = ((float[])(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class CompressorsGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
